[project]
name = "bybit-xbot"
version = "0.1.0"
description = "Telegram bot for detecting top-3 growing coins on Bybit Spot market."
authors = [
    {name = "Msh04q", email = "makbukshodiev@gmail.com"}
]

readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-telegram-bot (>=20.7,<21.0)",
    "nest-asyncio (>=1.6.0,<2.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "pybit (>=5.11.0,<6.0.0)",
    "httpx (>=0.25.2,<0.26.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false